version: '3.8'

services:
  db:
    container_name: db_container
    image: postgres:15
    environment:
      POSTGRES_USER: test_task_db
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
       - db:/data/postgres
    ports:
      - 5434:5432
    networks:
      - test_task
    restart: unless-stopped
   
  admin:
    container_name: admin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - admin:/var/lib/pgadmin

    ports:
      - 5050:80
    networks:
      - test_task
    restart: unless-stopped

networks:
  test_task:
    driver: bridge

volumes:
    db:
    admin: